<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LogicArrowsLauncher</AssemblyName>
    <Version>1.0.9</Version>
    <VersionPrefix>1.0.9</VersionPrefix>
    <AssemblyInformationalVersion>1.0.9</AssemblyInformationalVersion>
    <RootNamespace>LogicArrowsLauncher</RootNamespace>
    <UseAppHost>true</UseAppHost>
    <PublishTrimmed>false</PublishTrimmed>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>../assets/logic-arrows.ico</ApplicationIcon>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'win-x64'">
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>none</DebugType>
    <StripSymbols>true</StripSymbols>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="../assets/github/github-invertocat-white.png" LogicalName="LogicArrowsLauncher.github-invertocat-white.png" />
    <RuntimeHostConfigurationOption Include="System.Globalization.Invariant" Value="false" />
    <RuntimeHostConfigurationOption Include="System.Globalization.PredefinedCulturesOnly" Value="false" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
  </ItemGroup>
</Project>
